variables:
  APP_NAME: younesabdh-webapp
  REVIEW_APP_NAME: younesabdh-webapp-${CI_COMMIT_REF_NAME}
  REVIEW_API_ENDPOINT: ip10-0-3-4-cpk2ob3j2epg00b5vfrg-1993.direct.docker.labs.eazytraining.fr
  REVIEW_APP_ENDPOINT: ip10-0-3-4-cpk2ob3j2epg00b5vfrg-80.direct.docker.labs.eazytraining.fr
  STG_API_ENDPOINT: ip10-0-3-5-cpk2ob3j2epg00b5vfrg-1993.direct.docker.labs.eazytraining.fr
  STG_APP_ENDPOINT: ip10-0-3-5-cpk2ob3j2epg00b5vfrg-80.direct.docker.labs.eazytraining.fr
  PROD_API_ENDPOINT: ip10-0-3-6-cpk2ob3j2epg00b5vfrg-1993.direct.docker.labs.eazytraining.fr
  PROD_APP_ENDPOINT: ip10-0-3-6-cpk2ob3j2epg00b5vfrg-80.direct.docker.labs.eazytraining.fr
  INTERNAL_PORT: 5000
  EXTERNAL_PORT: 80
  TEST_PORT : 80
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}
  APP_CONTAINER_PORT: "80"
  APP_EXPOSED_PORT: "80"

image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build image
  - Test acceptation
  - Release image
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging
  - Deploy prod
  - Test prod

.test_template: &test
  image: alpine
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl "http://$DOMAIN" | grep -i "Dimension" 

docker-build:
  # Use the official docker image.
  stage: Build image
  script:
    - docker build -t  ${APP_NAME} .
    - docker save ${APP_NAME} > ${APP_NAME}.tar
  artifacts:
    paths:
      - ${APP_NAME}.tar    


test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker load < ${APP_NAME}.tar
    - docker run -d -p $APP_CONTAINER_PORT:$APP_EXPOSED_PORT -e PORT=$APP_CONTAINER_PORT --name webapp ${APP_NAME}
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker:$APP_CONTAINER_PORT" | grep -i "Dimension"

release image:
  stage: Release image
  script:
    - docker load < ${APP_NAME}.tar
    - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

# deploy review:
#   stage: Deploy review
#   environment:
#     name: review/$CI_COMMIT_REF_NAME
#     url: http://${EAZYLABS_IP}-${REVIEW_EXTERNAL_PORT}.${EAZYLABS_DOMAIN}
#     on_stop: stop review
#   only: 
#     - merge_requests
#   script:
#     - apk --no-cache add curl
#     - 'curl -i -v -X POST http://${API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${REVIEW_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}" 2>&1 | grep 200'
    
# stop review:
#   stage: Stop review
#   variables:
#     GIT_STRATEGY: none
#   environment:
#     name: review/$CI_COMMIT_REF_NAME
#     action: stop
#   only: 
#     - merge_requests
#   when: manual
#   script:
#     - apk --no-cache add curl
#     - 'curl -i -v -X DELETE http://${API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\"}"'

# deploy staging:
#   stage: Deploy staging
#   environment:
#     name: staging
#     url: http://${EAZYLABS_IP}-${STG_EXTERNAL_PORT}.${EAZYLABS_DOMAIN}
#   only:
#     - master
#   script:
#     - apk --no-cache add curl
#     - 'curl -i -v -X POST http://${API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${STG_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"  2>&1 | grep 200'

# test staging:
#   stage: Test staging
#   <<: *test
#   variables:
#     DOMAIN: ${EAZYLABS_IP}-${STG_EXTERNAL_PORT}.${EAZYLABS_DOMAIN}

# deploy prod:
#   stage: Deploy prod
#   environment:
#     name: prod
#     url: http://${EAZYLABS_IP}-${PROD_EXTERNAL_PORT}.${EAZYLABS_DOMAIN}
#   only: 
#     - main
#   script:
#     - apk --no-cache add curl
#     - 'curl -v -X POST http://${API_ENDPOINT}/prod -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${PROD_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}" 2>&1 | grep 200'

# test prod:
#   stage: Test prod
#   <<: *test
#   variables:
#     DOMAIN: ${EAZYLABS_IP}-${PROD_EXTERNAL_PORT}.${EAZYLABS_DOMAIN}
#   only:
#     - main