variables:
  APP_NAME: static-website-ay
  REVIEW_APP_NAME: static-website-ay-${CI_COMMIT_REF_NAME}
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}
  
  PROD_API_ENDPOINT: ip10-0-56-4-cpgrrnlcd84000a7dno0-1993.direct.docker.labs.eazytraining.fr
  PROD_APP_ENDPOINT: ip10-0-56-4-cpgrrnlcd84000a7dno0-80.direct.docker.labs.eazytraining.fr
  STG_API_ENDPOINT: ip10-0-56-5-cpgrrnlcd84000a7dno0-1993.direct.docker.labs.eazytraining.fr
  STG_APP_ENDPOINT: ip10-0-56-5-cpgrrnlcd84000a7dno0-80.direct.docker.labs.eazytraining.fr
  REVIEW_API_ENDPOINT: ip10-0-59-6-cpgtkb5cd84000a7dnsg-1993.direct.docker.labs.eazytraining.fr
  REVIEW_APP_ENDPOINT: ip10-0-59-6-cpgtkb5cd84000a7dnsg-80.direct.docker.labs.eazytraining.fr

  INTERNAL_PORT: 5000
  EXTERNAL_PORT: 80


  GIT_STRATEGY: none

image: docker:latest
default:
  interruptible: true
services: 
    - name: docker:dind
      alias: docker  



stages:
    - Build
    - Test acceptation
    - Release image
    - Deploy review
    - Stop review
    - Deploy staging
    - Test staging
    - Deploy prod
    - Test prod

.test_template: &test
  image: alpine
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl "http://${DOMAIN}" | grep -i "Dimension"  

.docker-build:
    stage: Build
    variables:
      GIT_STRATEGY: clone
    script:
        - docker build -t ${APP_NAME} .
        - docker save ${APP_NAME} > ${APP_NAME}.tar
    artifacts:
        paths:
            - ${APP_NAME}.tar

.test acceptation:
    stage: Test acceptation
    script:
        - docker load < ${APP_NAME}.tar
        - docker run -d -p 80:5000 -e PORT=5000 --name webapp-container ${APP_NAME}
        - sleep 5
        - apk --no-cache add curl
        - curl "http://docker:" | grep -i "Dimension"

.release image:
    stage: Release image
    script:
        - docker load < ${APP_NAME}.tar
        - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
        - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
        - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy review:
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://${REVIEW_APP_ENDPOINT}
    on_stop: stop review
  only:
    - master
  script:
    - apk --no-cache add curl
    - echo $APP_NAME
    - 'curl -X POST http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${REVIEW_APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - master
  when: manual  
  script:
    - apk --no-cache add curl
    - 'curl -X DELETE http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${REVIEW_APP_NAME}\"}"'

.deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: http://${STG_APP_ENDPOINT}
  only:
    - master
  interruptible: false
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${STG_API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

.test staging:
  <<: *test
  stage: Test staging
  variables:
    DOMAIN: ${STG_APP_ENDPOINT}

.deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: http://${PROD_APP_ENDPOINT}
  only:
    - master
  interruptible: false
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${PROD_API_ENDPOINT}/prod -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

.test prod:
  <<: *test
  stage: Test prod
  variables:
    DOMAIN: ${PROD_APP_ENDPOINT}
