variables:
  APP_NAME: static-website-ay
  REVIEW_APP_NAME: static-web-site-ay-${CI_COMMIT_REF_NAME}
  REVIEW_API_ENDPOINT: ip10-0-5-6-cpfj045cd84000a7dl70-1993.direct.docker.labs.eazytraining.fr
  REVIEW_APP_ENDPOINT: ip10-0-5-6-cpfj045cd84000a7dl70-80.direct.docker.labs.eazytraining.fr
  STG_API_ENDPOINT: ip10-0-5-5-cpfj045cd84000a7dl70-1993.direct.docker.labs.eazytraining.fr
  STG_APP_ENDPOINT: ip10-0-5-5-cpfj045cd84000a7dl70-80.direct.docker.labs.eazytraining.fr
  PROD_API_ENDPOINT: ip10-0-5-4-cpfj045cd84000a7dl70-1993.direct.docker.labs.eazytraining.fr
  PROD_APP_ENDPOINT: ip10-0-5-4-cpfj045cd84000a7dl70-80.direct.docker.labs.eazytraining.fr
  INTERNAL_PORT: 5000
  EXTERNAL_PORT: 80
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}

image: docker:latest
services: 
    - name: docker:dind
      alias: docker

stages:
    - Build
    - Test acceptation
    - Release image
    - Deploy review
    - Stop review
    - Deploy staging
    - Test staging
    - Deploy prod
    - Test prod

.test_template: &test
  image: alpine
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep -i "Dimension"  

docker-build:
    stage: Build
    script:
        - docker build -t static-website-ay .
        - docker save static-website-ay > static-website-ay.tar
    artifacts:
        paths:
            - static-website-ay.tar

test acceptation:
    stage: Test acceptation
    script:
        - docker load < static-website-ay.tar
        - docker run -d -p 80:5000 -e PORT=5000 --name static-website-ay-container static-website-ay
        - sleep 5
        - apk --no-cache add curl
        - curl "http://docker" | grep -i "Dimension"

release image:
    stage: Release image
    script:
        - docker load < static-website-ay.tar
        - docker tag static-website-ay "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
        - docker tag static-website-ay "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
        - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: http://${STG_APP_ENDPOINT}
  only:
    - master
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${STG_API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\",  \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"' 

deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: http://${PROD_APP_ENDPOINT}
  only:
    - master
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${PROD_API_ENDPOINT}/prod -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

deploy review:
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://${REVIEW_APP_ENDPOINT}
    on_stop: stop review
  only:
    - merge_requests
  variables:
    APP_NAME: ${REVIEW_APP_NAME}
  script:
    - apk --no-cache add curl
    - echo $APP_NAME
    - 'curl -X POST http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
    APP_NAME: ${REVIEW_APP_NAME}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual  
  script:
    - apk --no-cache add curl
    - 'curl -X DELETE http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\"}"'



test staging:
  <<: *test
  stage: Test staging
  only:
  - master
  variables:
    DOMAIN: ${STG_APP_ENDPOINT}


test prod:
  <<: *test
  stage: Test prod
  only:
    - master  
  variables:
    DOMAIN: ${PROD_APP_ENDPOINT}

